"use client";
import{useEffect,useMemo,useRef,useState}from'react';import html2canvas from'html2canvas';import{Area,Bar,BarChart,CartesianGrid,ComposedChart,LabelList,Legend,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis}from'recharts';import{abbr,integer,matrix,money,num,percent,sum}from'@/lib/data';
function Icon({type}){const paths={money:'M12 2v20M17 6.5c0-2-5-3-8-1.5s-2 5 1 6.5 8 0 7 4-2 5.5-8 3',chart:'M4 20V10h4v10M10 20V4h4v16M16 20v-7h4v7',phone:'M8 2h8a2 2 0 0 1 2 2v16a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2m3 17h2',star:'m12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1z',award:'M12 2 16 4v5c0 3-2 5-4 6-2-1-4-3-4-6V4zM9 14l-2 8 5-3 5 3-2-8',tag:'M3 12 12 3h7v7l-9 9zM16 7h.01',diamond:'m12 2 8 7-8 13L4 9z',globe:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20m-9 10h18M12 2c3 3 4 7 4 10s-1 7-4 10c-3-3-4-7-4-10s1-7 4-10',chat:'M21 12a8 8 0 0 1-8 8H6l-3 2 1-5a8 8 0 1 1 17-5',kiosk:'M7 2h10v13H7zM9 18h6M12 15v3'};return <span className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-gradient-to-br from-blue-500 to-voltz text-white"><svg viewBox="0 0 24 24" className="h-7 w-7" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d={paths[type]}/></svg></span>}
function models(rows,key){const m=matrix(rows,key),total=rows?.find(r=>r[key]==='Total'),months=m.months.filter(x=>!total||(num(total[x.key])??0)>0);return m.items.map(r=>{const vals=months.map(x=>num(r[x.key]));return{name:String(r[key]),total:num(r.Coluna13)??sum(vals),share:num(r.Coluna14)??0,points:months.map((x,i)=>({mes:x.label,valor:vals[i]??0}))}})}
function Panel({title,icon,big,sub,children}){return <section className="flex min-w-0 flex-col rounded-3xl border border-slate-200 bg-white p-5 shadow-card"><h2 className="text-xl font-bold text-voltz">{title}</h2><div className="my-4 flex items-center gap-5 rounded-2xl border border-blue-200 p-4"><Icon type={icon}/><div><div className="text-4xl font-extrabold text-voltz">{big}</div><div className="text-lg text-voltz">{sub}</div></div></div><div className="flex-1">{children}</div></section>}
function MixRow({icon,name,value,share,max,currency=false}){return <div className="grid grid-cols-[48px_1fr_1.25fr_104px] items-center gap-3 border-b border-slate-100 py-3"><Icon type={icon}/><b className="text-sm text-voltz">{name}</b><div className="h-8 overflow-hidden rounded bg-blue-50"><div className="h-full rounded bg-gradient-to-r from-blue-500 to-voltz" style={{width:`${Math.max(2,value/max*100)}%`}}/></div><div className="text-right"><b className="text-lg text-voltz">{percent(share)}</b><div className="mt-1 whitespace-nowrap text-xs font-semibold text-slate-600">{currency?money(value):abbr(value)}</div></div></div>}
function Sparkline({data}){if(!data.length)return null;const width=310,height=92,padX=28,padTop=22,padBottom=18,values=data.map(x=>x.valor),min=Math.min(...values),max=Math.max(...values),range=max-min||1;const points=data.map((item,index)=>{const x=padX+(index*(width-padX*2))/Math.max(1,data.length-1);const y=padTop+((max-item.valor)/range)*(height-padTop-padBottom);return{...item,x,y}});const path=points.map((p,i)=>`${i?'L':'M'} ${p.x} ${p.y}`).join(' ');return <svg viewBox={`0 0 ${width} ${height}`} className="h-full w-full overflow-visible" role="img"><line x1={padX} y1={height-padBottom+2} x2={width-padX} y2={height-padBottom+2} stroke="#cbd5e1"/><path d={path} fill="none" stroke="#0A2D87" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/>{points.map((point,index)=><g key={`${point.mes}-${index}`}><circle cx={point.x} cy={point.y} r="4" fill="#fff" stroke="#0A2D87" strokeWidth="3"/><text x={point.x} y={point.y-10} textAnchor="middle" fontSize="9" fontWeight="700" fill="#566174">{abbr(point.valor)}</text><text x={point.x} y={height-3} textAnchor="middle" fontSize="8" fill="#64748b">{point.mes}</text></g>)}</svg>}
function TrendRow({icon,item}){return <div className="grid grid-cols-[48px_112px_minmax(0,1fr)] items-center gap-3 border-b border-slate-100 py-2"><Icon type={icon}/><div><b className="text-sm text-voltz">{item.name}</b><div className="font-bold text-voltz">{integer(item.total)}</div><div className="text-sm font-bold text-voltz">{percent(item.share)}</div></div><div className="h-[122px] min-w-0 overflow-visible"><Sparkline data={item.points}/></div></div>}
function Council({parcel,plans,channels,total,months}){const pmax=Math.max(...parcel.map(x=>x.total)),cmax=Math.max(...channels.map(x=>x.total));return <div className="council grid h-[820px] grid-cols-3 gap-4"><Panel title={`1. Arrecadação por plano | ${months}`} icon="money" big={abbr(total)} sub="Total de parcelas pagas"><div className="space-y-3">{parcel.map((x,i)=><MixRow key={x.name} icon={['award','star','tag','diamond'][i]} name={x.name} value={x.total} share={x.share} max={pmax} currency/>)}</div></Panel><Panel title={`2. Adesões por plano | ${months}`} icon="chart" big={integer(sum(plans.map(x=>x.total)))} sub="adesões"><div className="space-y-3">{plans.map((x,i)=><TrendRow key={x.name} icon={['star','tag','diamond'][i]} item={x}/>)}</div></Panel><Panel title={`3. Adesões por canal | ${months}`} icon="phone" big={integer(sum(channels.map(x=>x.total)))} sub="adesões digitais"><div className="space-y-3">{channels.map((x,i)=><MixRow key={x.name} icon={['phone','globe','chat','kiosk'][i]} name={x.name} value={x.total} share={x.share} max={cmax}/>)}</div></Panel></div>}
function Kpi({label,value,detail,change}){const color=change==null?'text-slate-400':change>=0?'text-emerald-600':'text-rose-600';return <article className="rounded-3xl border border-slate-200 border-l-4 border-l-voltz bg-white p-5 shadow-card"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p>{detail&&<p className="mt-1 text-xs text-slate-500">{detail}</p>}{change!==undefined&&<p className={'mt-2 text-sm font-bold '+color}>{change==null?'Variação indisponível':`${change>=0?'▲':'▼'} ${percent(Math.abs(change))} vs. mês anterior`}</p>}</article>}
function ChartCard({title,children}){return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-card"><h2 className="text-lg font-bold">{title}</h2><div className="mt-4">{children}</div></section>}
function BudgetChart({data}){return <div className="h-[430px]"><ResponsiveContainer><ComposedChart data={data} margin={{top:35,right:10}}><CartesianGrid vertical={false} strokeDasharray="3 5"/><XAxis dataKey="mes"/><YAxis yAxisId="m" tickFormatter={abbr}/><YAxis yAxisId="p" orientation="right" tickFormatter={percent}/><Tooltip formatter={(v,n)=>n==='Atingimento'?percent(Number(v)):money(Number(v))}/><Legend iconType="circle"/><Bar isAnimationActive={false} yAxisId="m" dataKey="planejado" name="Planejado" fill="#b9c7e8" radius={[10,10,10,10]}><LabelList dataKey="planejado" position="top" formatter={abbr}/></Bar><Bar isAnimationActive={false} yAxisId="m" dataKey="realizado" name="Realizado" fill="#0A2D87" radius={[10,10,10,10]}><LabelList dataKey="realizado" position="top" formatter={abbr}/></Bar><Line isAnimationActive={false} yAxisId="p" type="monotone" dataKey="atingimento" name="Atingimento" stroke="#12a66a" strokeWidth={4} dot={{r:5}}><LabelList dataKey="atingimento" position="top" formatter={percent}/></Line></ComposedChart></ResponsiveContainer></div>}
function StackChart({data,series}){const colors=['#0A2D87','#2871d4','#12a66a','#f59e0b'];return <div className="h-[430px]"><ResponsiveContainer><BarChart data={data}><CartesianGrid vertical={false} strokeDasharray="3 5"/><XAxis dataKey="mes"/><YAxis tickFormatter={abbr}/><Legend iconType="circle"/><Tooltip formatter={v=>money(Number(v))}/>{series.map((name,index)=><Bar isAnimationActive={false} key={name} dataKey={name} stackId="a" fill={colors[index%colors.length]} radius={[8,8,8,8]}><LabelList dataKey={name} position="center" formatter={v=>v?abbr(v):''} fill="#fff"/></Bar>)}</BarChart></ResponsiveContainer></div>}
function SmallChart({data}){return <div className="h-[255px]"><ResponsiveContainer><BarChart data={data} margin={{top:30,right:8,left:-12}}><CartesianGrid vertical={false} strokeDasharray="3 5"/><XAxis dataKey="mes"/><YAxis tickFormatter={abbr}/><Tooltip formatter={v=>integer(Number(v))}/><Bar isAnimationActive={false} dataKey="valor" fill="#0A2D87" radius={[9,9,9,9]}><LabelList dataKey="valor" position="top" formatter={abbr}/></Bar></BarChart></ResponsiveContainer></div>}
function GrowthChart({data}){return <div className="h-[430px]"><ResponsiveContainer><ComposedChart data={data} margin={{top:30}}><CartesianGrid vertical={false} strokeDasharray="3 5"/><XAxis dataKey="mes"/><YAxis yAxisId="b" tickFormatter={abbr}/><YAxis yAxisId="p" orientation="right" tickFormatter={percent}/><Legend/><Area isAnimationActive={false} yAxisId="b" dataKey="total_base" name="Total da base" stroke="#0A2D87" strokeWidth={4} fill="#dce7ff"><LabelList dataKey="total_base" position="top" formatter={abbr}/></Area><Line isAnimationActive={false} yAxisId="p" dataKey="crescimento_percentual_base" name="Crescimento percentual" stroke="#12a66a" strokeWidth={4}><LabelList dataKey="crescimento_percentual_base" position="top" formatter={percent}/></Line></ComposedChart></ResponsiveContainer></div>}
function monthVariation(points){if(points.length<2)return null;const previous=points[points.length-2].valor,current=points[points.length-1].valor;return previous===0?null:(current-previous)/previous}
export default function Dashboard(){const[data,setData]=useState(null),[view,setView]=useState('council'),[budgetTab,setBudgetTab]=useState('consolidado'),[growthTab,setGrowthTab]=useState('plan'),[exporting,setExporting]=useState(false);const ref=useRef(null);useEffect(()=>{fetch('/dashboard.json',{cache:'no-store'}).then(r=>r.json()).then(setData)},[]);const budget=useMemo(()=>{const rows=data?.orcadoVsRealizado?.[budgetTab]??[],key=Object.keys(rows[0]??{}).find(k=>!['Coluna1','Coluna2','Coluna3'].includes(k));return key?rows.filter(r=>r[key]!=='Mês'&&num(r.Coluna1)!==null).map(r=>({mes:String(r[key]),planejado:num(r.Coluna1),realizado:num(r.Coluna2),atingimento:num(r.Coluna3)})):[]},[data,budgetTab]);if(!data)return <main className="grid min-h-screen place-items-center">Carregando...</main>;
const parcel=models(data.parcelasPagas?.dados,'Share de Planos');
const plans=models(data.crescimentoBaseVsAdesoes?.adesaoPlano,'Share de Planos');
const channels=models(data.crescimentoBaseVsAdesoes?.adesaoCanal,'Share de Canais');
const totalRow=data.parcelasPagas?.dados?.find(x=>x['Share de Planos']==='Total');
const total=num(totalRow?.Coluna13)??sum(parcel.map(x=>x.total));
const months=parcel[0]?.points.length?`Jan a ${parcel[0].points[parcel[0].points.length-1].mes}/2026`:'2026';
const parcelMatrix=matrix(data.parcelasPagas?.dados,'Share de Planos');
const parcelData=parcelMatrix.months.map(month=>{
  const point={mes:month.label};
  parcelMatrix.items.forEach(item=>{point[String(item['Share de Planos'])]=num(item[month.key])??0});
  return point;
}).filter(point=>parcelMatrix.items.some(item=>Number(point[String(item['Share de Planos'])])>0));
const growthRows=data.crescimentoBaseVsAdesoes?.crescimentoBase??[];
const growth=growthRows.map(item=>({
  mes:String(item.mes??''),
  total_base:num(item.total_base),
  crescimento_percentual_base:num(item.crescimento_percentual_base)
})).filter(item=>item.mes&&item.total_base!==null);
const validBase=growth.map(item=>item.total_base).filter(value=>value!==null);
const growthPct=growth.map(item=>item.crescimento_percentual_base).filter(value=>value!==null);
const adh=sum(growthRows.map(item=>num(item.adesoes)));
const can=sum(growthRows.map(item=>num(item.cancelamentos)));
const net=sum(growthRows.map(item=>num(item.crescimento_liquido)));
const realized=budget.filter(item=>item.realizado!==null);
const planned=sum(realized.map(item=>item.planejado));
const actual=sum(realized.map(item=>item.realizado));
async function png(){if(!ref.current||exporting)return;setExporting(true);try{ref.current.classList.add('export-mode');await document.fonts.ready;await new Promise(r=>setTimeout(r,300));const canvas=await html2canvas(ref.current,{backgroundColor:'#f4f6f9',scale:2,width:1920,height:1080,windowWidth:1920,windowHeight:1080});const link=document.createElement('a');link.download=`dashboard-voltz-${view}-16x9.png`;link.href=canvas.toDataURL('image/png',1);link.click()}finally{ref.current.classList.remove('export-mode');setExporting(false)}}
return <div className="min-h-screen px-2 py-4"><main ref={ref} className="export-canvas mx-auto"><header className="mb-4 rounded-3xl bg-voltz px-7 py-5 text-white md:flex md:items-center md:justify-between"><div><h1 className="text-3xl font-bold">Dashboard Executivo · Voltz</h1><p>Dados carregados de dashboard.json</p></div><div className="flex gap-3"><select value={view} onChange={e=>setView(e.target.value)} className="rounded-2xl bg-white px-4 py-3 text-slate-800"><option value="council">Resumo conselho</option><option value="budget">Orçado vs Realizado</option><option value="parcel">Parcelas Pagas</option><option value="growth">Crescimento da Base vs Adesões</option></select><button data-html2canvas-ignore onClick={png} className="rounded-2xl border border-white/30 px-4">{exporting?'Preparando...':'↓ Exportar PNG 16:9'}</button></div></header>
{view==='council'&&<Council parcel={parcel} plans={plans} channels={channels} total={total} months={months}/>} 
{view==='budget'&&<div className="space-y-4"><div className="flex gap-2">{['baseline','alavanca','consolidado'].map(t=><button key={t} onClick={()=>setBudgetTab(t)} className={'rounded-2xl px-4 py-2 capitalize '+(budgetTab===t?'bg-voltz text-white':'bg-white')}>{t}</button>)}</div><div className="grid grid-cols-4 gap-3"><Kpi label="Planejado acumulado" value={money(planned)}/><Kpi label="Realizado acumulado" value={money(actual)}/><Kpi label="Atingimento" value={percent(planned?actual/planned:0)}/><Kpi label="Diferença" value={money(actual-planned)}/></div><ChartCard title={`Orçado vs Realizado · ${budgetTab}`}><BudgetChart data={budget}/></ChartCard></div>}
{view==='parcel'&&<div className="space-y-4"><div className="grid grid-cols-4 gap-3"><Kpi label="Total arrecadado" value={money(total)}/><Kpi label="Quantidade de planos" value={String(parcel.length)}/><Kpi label="Meses com arrecadação" value={String(parcelData.length)}/><Kpi label="Média mensal" value={money(parcelData.length?total/parcelData.length:0)}/></div><div className="grid grid-cols-4 gap-3">{parcel.map(x=><Kpi key={x.name} label={x.name} value={money(x.total)} detail={`${percent(x.share)} de representatividade`}/>)}</div><ChartCard title="Parcelas pagas por plano"><StackChart data={parcelData} series={parcel.map(x=>x.name)}/></ChartCard></div>}
{view==='growth'&&<div className="space-y-4"><div className="flex gap-2">{[['plan','Adesão por Plano'],['channel','Adesão por Canal'],['base','Crescimento da Base']].map(([k,l])=><button key={k} onClick={()=>setGrowthTab(k)} className={'rounded-2xl px-4 py-2 '+(growthTab===k?'bg-voltz text-white':'bg-white')}>{l}</button>)}</div>{growthTab==='plan'&&<><div className="grid grid-cols-3 gap-3">{plans.map(x=><Kpi key={x.name} label={x.name} value={integer(x.total)} detail={`${percent(x.share)} de representatividade`} change={monthVariation(x.points)}/>)}</div><div className="grid grid-cols-3 gap-3">{plans.map(x=><ChartCard key={x.name} title={x.name}><SmallChart data={x.points}/></ChartCard>)}</div></>}{growthTab==='channel'&&<><div className="grid grid-cols-4 gap-3">{channels.map(x=><Kpi key={x.name} label={x.name} value={integer(x.total)} detail={`${percent(x.share)} de representatividade`} change={monthVariation(x.points)}/>)}</div><div className="grid grid-cols-2 gap-3">{channels.map(x=><ChartCard key={x.name} title={x.name}><SmallChart data={x.points}/></ChartCard>)}</div></>}{growthTab==='base'&&<><div className="grid grid-cols-4 gap-3"><Kpi label="Base atual" value={integer(validBase[validBase.length-1]??0)} change={growthPct[growthPct.length-1]??null}/><Kpi label="Adesões acumuladas" value={integer(adh)}/><Kpi label="Cancelamentos acumulados" value={integer(can)}/><Kpi label="Crescimento líquido" value={integer(net)}/></div><ChartCard title="Crescimento da Base"><GrowthChart data={growth}/></ChartCard></>}</div>}</main></div>}
